import {
  User,
  Department,
  AcademicClass,
  Subject,
  SyllabusItem,
  Assignment,
  InstitutionalEvent,
  ProjectGroup,
  QuizQuestion,
  StudentLearningProfile,
  WhatsAppNotification,
} from './types';

// The 15 Standard Quiz Questions for Numerical Learning Profile Assessment (Sections 84-96)
export const LEARNING_PROFILE_QUESTIONS: QuizQuestion[] = [
  // Section 1: Study Time
  {
    id: 1,
    section: 'Study Time',
    question: 'How much time can you normally spend studying on a weekday?',
    field: 'weekdayAvailabilityScore',
    helpText: 'Used to calculate daily workload capacity and prevent overloaded schedules.',
    options: [
      { text: 'Less than 1 hour', value: 1 },
      { text: '1–2 hours', value: 2 },
      { text: '2–3 hours', value: 3 },
      { text: '3–4 hours', value: 4 },
      { text: 'More than 4 hours', value: 5 },
    ],
  },
  {
    id: 2,
    section: 'Study Time',
    question: 'How much time can you normally study on weekends?',
    field: 'weekendAvailabilityScore',
    helpText: 'Used to distribute larger study tasks across weekdays and weekend blocks.',
    options: [
      { text: 'Less than 2 hours', value: 1 },
      { text: '2–4 hours', value: 2 },
      { text: '4–6 hours', value: 3 },
      { text: 'More than 6 hours', value: 4 },
    ],
  },
  // Section 2: Theory Learning
  {
    id: 3,
    section: 'Theory Learning',
    question: 'When learning a new theory or concept, what usually describes you best?',
    field: 'theoryLearningRequirement',
    helpText: 'Higher requirement adds dedicated comprehension time before problem solving.',
    options: [
      { text: 'I understand it after reading once.', value: 1 },
      { text: 'I need to read it 2–3 times.', value: 2 },
      { text: 'I need examples before I understand it.', value: 3 },
      { text: 'I need someone or something to explain it differently.', value: 4 },
      { text: 'I need to practice questions before I understand it.', value: 5 },
    ],
  },
  {
    id: 4,
    section: 'Theory Learning',
    question: 'When studying a theory chapter, which approach works best for you?',
    field: 'preferredTheoryMethod',
    helpText: 'Determines study recommendations and practice reminders.',
    options: [
      { text: 'Reading the chapter', value: 1, metaKey: 'reading' },
      { text: 'Watching an explanation / video', value: 2, metaKey: 'video' },
      { text: 'Making summary notes', value: 3, metaKey: 'notes' },
      { text: 'Seeing worked examples', value: 4, metaKey: 'examples' },
      { text: 'Practicing questions directly', value: 5, metaKey: 'practice' },
    ],
  },
  // Section 3: Problem Solving
  {
    id: 5,
    section: 'Problem Solving',
    question: 'When you see a difficult problem or equation, what usually happens?',
    field: 'problemUnderstandingScore',
    helpText: 'Helps scale problem-solving duration multipliers.',
    options: [
      { text: 'I understand what to do immediately.', value: 1 },
      { text: 'I understand after thinking for a while.', value: 2 },
      { text: 'I understand after seeing a similar example.', value: 3 },
      { text: 'I need a hint or step-by-step breakdown.', value: 4 },
      { text: 'I usually struggle to understand where to start.', value: 5 },
    ],
  },
  {
    id: 6,
    section: 'Problem Solving',
    question: 'How do you feel about solving multiple problems at once?',
    field: 'problemBatchPreference',
    helpText: 'Used when splitting large quantitative assignments into manageable chunks.',
    options: [
      { text: 'I prefer many problems together in one sitting.', value: 1, metaKey: 'all' },
      { text: 'I prefer 5–10 problems at a time.', value: 2, metaKey: '5-10' },
      { text: 'I prefer 2–5 problems at a time.', value: 3, metaKey: '2-5' },
      { text: 'I prefer one problem at a time.', value: 4, metaKey: 'single' },
    ],
  },
  // Section 4: Focus & Breaks
  {
    id: 7,
    section: 'Focus & Breaks',
    question: 'How long can you usually study before needing a break?',
    field: 'focusDurationScore',
    helpText: 'Used to calibrate ideal task block durations and study intervals.',
    options: [
      { text: '15 minutes (Micro sprints)', value: 1 },
      { text: '20–30 minutes (Standard Pomodoro)', value: 2 },
      { text: '30–45 minutes (Deep blocks)', value: 3 },
      { text: '45–60 minutes (Extended focus)', value: 4 },
      { text: 'More than 60 minutes (Deep flow state)', value: 5 },
    ],
  },
  {
    id: 8,
    section: 'Focus & Breaks',
    question: 'What usually happens when you study for a long time without a break?',
    field: 'longSessionToleranceScore',
    helpText: 'Prevents cognitive exhaustion by setting hard session caps.',
    options: [
      { text: 'I stay focused throughout.', value: 1 },
      { text: 'I become slightly distracted.', value: 2 },
      { text: 'I lose concentration noticeably.', value: 3 },
      { text: 'I become stressed or tired.', value: 4 },
      { text: 'I stop studying completely.', value: 5 },
    ],
  },
  // Section 5: Task Preference
  {
    id: 9,
    section: 'Task Preference',
    question: 'Which type of academic task takes you the longest?',
    field: 'longestTaskType',
    helpText: 'Applies personalized duration multipliers to specific task types.',
    options: [
      { text: 'Reading theory', value: 1, metaKey: 'reading_theory' },
      { text: 'Understanding complex theory', value: 2, metaKey: 'understanding_theory' },
      { text: 'Solving mathematical/algorithmic problems', value: 3, metaKey: 'solving_problems' },
      { text: 'Writing lab reports & long essays', value: 4, metaKey: 'writing_answers' },
      { text: 'Memorizing terminology & facts', value: 5, metaKey: 'memorizing' },
      { text: 'Group projects & software builds', value: 6, metaKey: 'projects' },
    ],
  },
  {
    id: 10,
    section: 'Task Preference',
    question: 'Which type of task do you prefer to finish first?',
    field: 'taskOrderingPreference',
    helpText: 'Guides the daily task ordering hierarchy without missing urgent deadlines.',
    options: [
      { text: 'Easy tasks first (Build momentum)', value: 1, metaKey: 'easy_first' },
      { text: 'Difficult tasks first (Eat the frog)', value: 2, metaKey: 'difficult_first' },
      { text: 'Shortest tasks first (Quick wins)', value: 3, metaKey: 'short_first' },
      { text: 'Tasks with the closest deadline (Urgency-based)', value: 4, metaKey: 'closest_deadline' },
      { text: 'Flexible / Depends on my mood', value: 5, metaKey: 'flexible' },
    ],
  },
  // Section 6: Revision
  {
    id: 11,
    section: 'Revision',
    question: 'How often do you normally need to revise something before remembering it?',
    field: 'revisionNeedScore',
    helpText: 'Automatically schedules periodic spaced-repetition slots.',
    options: [
      { text: 'Once is enough.', value: 1 },
      { text: '2–3 times over the term.', value: 2 },
      { text: '4–5 times for solid retention.', value: 3 },
      { text: 'Frequently throughout every week.', value: 4 },
      { text: 'I forget quickly without constant revision.', value: 5 },
    ],
  },
  {
    id: 12,
    section: 'Revision',
    question: 'When do you prefer to revise newly learned concepts?',
    field: 'revisionTimingPreference',
    helpText: 'Aligns revision session suggestions with your natural retention cycle.',
    options: [
      { text: 'Same day after class', value: 1, metaKey: 'same_day' },
      { text: 'The next morning / next day', value: 2, metaKey: 'next_day' },
      { text: 'Every few days', value: 3, metaKey: 'few_days' },
      { text: 'Weekly review sessions on weekends', value: 4, metaKey: 'weekly' },
      { text: 'Directly before exams / module tests', value: 5, metaKey: 'before_exam' },
    ],
  },
  // Section 7: Stress / Workload Sensitivity
  {
    id: 13,
    section: 'Stress / Workload Sensitivity',
    question: 'How stressed do you usually feel when you have multiple deadlines clustered together?',
    field: 'stressSensitivityScore',
    helpText: 'Academic workload sensitivity used to determine task spreading aggression.',
    options: [
      { text: '1 — Very comfortable (Handle high pressure easily)', value: 1 },
      { text: '2 — Comfortable', value: 2 },
      { text: '3 — Moderate pressure', value: 3 },
      { text: '4 — Stressed (Need early warnings)', value: 4 },
      { text: '5 — Very stressed (Need aggressive task splitting)', value: 5 },
    ],
  },
  // Section 8: Multiple-Deadline Difficulty
  {
    id: 14,
    section: 'Multiple-Deadline Difficulty',
    question: 'When you face multiple competing deadlines, what is your biggest hurdle?',
    field: 'deadlineDifficultyType',
    helpText: 'Tailors the AI recommendations to address your specific challenge.',
    options: [
      { text: 'I do not know where to start.', value: 1, metaKey: 'dont_know_start' },
      { text: 'I underestimate how long tasks will take.', value: 2, metaKey: 'underestimate_time' },
      { text: 'I procrastinate until the final day.', value: 3, metaKey: 'procrastination' },
      { text: 'I get overwhelmed and freeze.', value: 4, metaKey: 'overwhelmed' },
      { text: 'I forget about approaching deadlines.', value: 5, metaKey: 'forget_deadlines' },
      { text: 'I spend way too much time perfecting one task.', value: 6, metaKey: 'too_much_time_one' },
    ],
  },
  // Section 9: Assignment Splitting
  {
    id: 15,
    section: 'Assignment Splitting',
    question: 'How would you prefer large projects or lab reports to be divided by the AI?',
    field: 'assignmentSplittingPreference',
    helpText: 'Controls the automated milestone generation algorithm.',
    options: [
      { text: 'Small daily bite-sized sub-tasks', value: 1, metaKey: 'small_daily' },
      { text: 'Larger task blocks every few days', value: 2, metaKey: 'larger_few_days' },
      { text: 'Front-load: Finish it as early as possible', value: 3, metaKey: 'finish_early' },
      { text: 'Spread evenly across all days until deadline', value: 4, metaKey: 'spread_evenly' },
      { text: 'Let the EDU-WAVE AI optimizer decide based on load', value: 5, metaKey: 'ai_decide' },
    ],
  },
];

// Initial Admin User (Section 8 & 60)
export const INITIAL_ADMIN_USER: User = {
  id: 'usr-admin-1',
  unique_id: 'ADMIN@123',
  email: 'admin@eduweave.edu',
  role: 'admin',
  full_name: 'Dr. Robert Sterling',
  avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
  bio: 'Platform Administrator & Provost of Academic Coordination.',
  must_change_password: false,
  profile_completed: true,
  quiz_completed: true,
  whatsapp_enabled: true,
  created_at: '2026-08-01T00:00:00Z',
};

// Initial Seed Users (Prepared for First-Login Demonstration)
export const SEED_USERS: User[] = [
  INITIAL_ADMIN_USER,
  {
    id: 'usr-hod-1',
    unique_id: 'HOD-2001',
    email: 'm.vance@eduweave.edu',
    role: 'hod',
    full_name: 'Dr. Marcus Vance',
    department_id: 'dept-1',
    department_name: 'Computer Science & Engineering',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    phone: '+1 (555) 234-5678',
    bio: 'Head of Department, Distributed Computing & AI Systems.',
    skills: ['Department Governance', 'Curriculum Design', 'Faculty Mentorship'],
    must_change_password: true,
    profile_completed: false,
    quiz_completed: false,
    whatsapp_enabled: true,
    created_at: '2026-08-05T00:00:00Z',
  },
  {
    id: 'usr-tch-1',
    unique_id: 'TCH-3001',
    email: 'e.rostova@eduweave.edu',
    role: 'teacher',
    full_name: 'Prof. Elena Rostova',
    department_id: 'dept-1',
    department_name: 'Computer Science & Engineering',
    class_id: 'cls-1',
    class_name: 'BCA - Section A',
    section: 'A',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    phone: '+1 (555) 345-6789',
    bio: 'Associate Professor in Algorithms and Database Architectures.',
    skills: ['Database Systems', 'Data Structures', 'Student Mentoring'],
    must_change_password: true,
    profile_completed: false,
    quiz_completed: false,
    whatsapp_enabled: true,
    created_at: '2026-08-08T00:00:00Z',
  },
  {
    id: 'usr-stu-1',
    unique_id: 'STU-4001',
    email: 'alex.chen@student.eduweave.edu',
    role: 'student',
    full_name: 'Alex Chen',
    department_id: 'dept-1',
    department_name: 'Computer Science & Engineering',
    class_id: 'cls-1',
    class_name: 'BCA - Section A',
    section: 'A',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    phone: '+1 (555) 890-1234',
    bio: '2nd Year BCA Student passionate about Cloud Architectures and Web Engineering.',
    skills: ['Python', 'SQL', 'Lab Assisting', 'Public Speaking'],
    must_change_password: true,
    profile_completed: false,
    quiz_completed: false,
    whatsapp_enabled: true,
    created_at: '2026-08-10T00:00:00Z',
  },
];

export const SEED_DEPARTMENTS: Department[] = [
  {
    id: 'dept-1',
    name: 'Computer Science & Engineering',
    code: 'CSE',
    hod_id: 'usr-hod-1',
    hod_name: 'Dr. Marcus Vance',
    faculty_count: 8,
    student_count: 140,
    class_count: 4,
    description: 'Undergraduate and graduate programs in Computing, Software Engineering & AI.',
  },
  {
    id: 'dept-2',
    name: 'Natural & Biological Sciences',
    code: 'NBS',
    faculty_count: 6,
    student_count: 95,
    class_count: 3,
    description: 'Empirical sciences, molecular biology, and bioenergetics research.',
  },
  {
    id: 'dept-3',
    name: 'Mathematical Sciences',
    code: 'MATH',
    faculty_count: 5,
    student_count: 110,
    class_count: 3,
    description: 'Pure and applied mathematics, discrete optimization, and statistics.',
  },
];

export const SEED_CLASSES: AcademicClass[] = [
  {
    id: 'cls-1',
    name: 'BCA - Section A',
    code: 'BCA-301',
    section: 'A',
    department_id: 'dept-1',
    department_name: 'Computer Science & Engineering',
    term: 'Semester 3 (Fall 2026)',
    room_number: 'Lab Block C-204',
    teacher_id: 'usr-tch-1',
    teacher_name: 'Prof. Elena Rostova',
    subject: 'Database Management Systems',
    student_count: 42,
  },
  {
    id: 'cls-2',
    name: 'BCA - Section B',
    code: 'BCA-302',
    section: 'B',
    department_id: 'dept-1',
    department_name: 'Computer Science & Engineering',
    term: 'Semester 3 (Fall 2026)',
    room_number: 'Lab Block C-206',
    teacher_id: 'usr-tch-1',
    teacher_name: 'Prof. Elena Rostova',
    subject: 'Database Management Systems',
    student_count: 38,
  },
  {
    id: 'cls-3',
    name: 'BSc CS - Section A',
    code: 'BSC-201',
    section: 'A',
    department_id: 'dept-1',
    department_name: 'Computer Science & Engineering',
    term: 'Semester 2 (Fall 2026)',
    room_number: 'Hall A-102',
    subject: 'Data Structures & Algorithms',
    student_count: 45,
  },
];

export const SEED_SUBJECTS: Subject[] = [
  {
    id: 'subj-1',
    name: 'Database Management Systems',
    code: 'CS-301',
    department_id: 'dept-1',
    department_name: 'Computer Science & Engineering',
    semester_year: 'Semester 3',
    teacher_id: 'usr-tch-1',
    teacher_name: 'Prof. Elena Rostova',
    class_id: 'cls-1',
    class_name: 'BCA - Section A',
    credits: 4,
  },
  {
    id: 'subj-2',
    name: 'Data Structures & Algorithms',
    code: 'CS-302',
    department_id: 'dept-1',
    department_name: 'Computer Science & Engineering',
    semester_year: 'Semester 3',
    class_id: 'cls-1',
    class_name: 'BCA - Section A',
    credits: 4,
  },
  {
    id: 'subj-3',
    name: 'Discrete Mathematics',
    code: 'MA-201',
    department_id: 'dept-3',
    department_name: 'Mathematical Sciences',
    semester_year: 'Semester 3',
    class_id: 'cls-1',
    class_name: 'BCA - Section A',
    credits: 3,
  },
];

export const SEED_SYLLABI: SyllabusItem[] = [
  {
    id: 'syl-1',
    class_id: 'cls-1',
    class_name: 'BCA - Section A',
    subject_name: 'Database Management Systems',
    topic_name: 'Relational Algebra & Normalization',
    unit_number: 'Unit 3.2',
    key_concepts: ['1NF/2NF/3NF/BCNF', 'Functional Dependencies', 'Lossless Join Decomposition', 'Query Optimization'],
    content_text: 'Formal mathematical criteria for decomposition of relational schemas into Boyce-Codd Normal Form without losing dependency preservation.',
    textbook_reference: 'Silberschatz & Korth: Database System Concepts 7th Ed, Ch 8, p.320–355',
    teacher_notes_snippets: 'Make sure students verify functional dependencies before testing 3NF vs BCNF!',
    uploaded_by: 'usr-tch-1',
    created_at: '2026-08-11T09:00:00Z',
  },
  {
    id: 'syl-2',
    class_id: 'cls-1',
    class_name: 'BCA - Section A',
    subject_name: 'Data Structures & Algorithms',
    topic_name: 'Dynamic Programming & Graph Traversal',
    unit_number: 'Unit 4.1',
    key_concepts: ['Memoization', 'Tabulation', 'Bellman-Ford', 'Dijkstra Shortest Path'],
    content_text: 'Optimal substructure and overlapping subproblems in multi-stage graph path optimizations.',
    textbook_reference: 'CLRS Introduction to Algorithms 4th Ed, Ch 15, p.380–412',
    teacher_notes_snippets: 'Highlight recurrence relations prior to code implementation.',
    uploaded_by: 'usr-tch-1',
    created_at: '2026-08-12T10:00:00Z',
  },
];

export const SEED_ASSIGNMENTS: Assignment[] = [
  {
    id: 'asg-1',
    title: 'Database Normalization & SQL Triggers Project',
    description: 'Design a normalized 3NF schema for an e-commerce platform and implement audit triggers in PostgreSQL.',
    class_id: 'cls-1',
    class_name: 'BCA - Section A',
    subject_name: 'Database Management Systems',
    topic_tag: 'Relational Normalization',
    teacher_id: 'usr-tch-1',
    teacher_name: 'Prof. Elena Rostova',
    due_date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    due_time: '23:59',
    priority_level: 'high',
    estimated_hours: 4.5,
    status: 'upcoming',
    created_at: new Date().toISOString(),
    sub_tasks: [
      {
        id: 'st-1',
        step_number: 1,
        title: 'Draft Entity-Relationship diagram and functional dependency list',
        due_date: new Date(Date.now() + 1 * 86400000).toISOString().split('T')[0],
        completed: false,
        estimated_minutes: 60,
      },
      {
        id: 'st-2',
        step_number: 2,
        title: 'Execute BCNF normalization decomposition and test for lossless join',
        due_date: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
        completed: false,
        estimated_minutes: 90,
      },
      {
        id: 'st-3',
        step_number: 3,
        title: 'Write SQL schema script and implement PL/pgSQL trigger procedures',
        due_date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
        completed: false,
        estimated_minutes: 75,
      },
      {
        id: 'st-4',
        step_number: 4,
        title: 'Final query optimization benchmarking & report submission',
        due_date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
        completed: false,
        estimated_minutes: 45,
      },
    ],
  },
  {
    id: 'asg-2',
    title: 'Shortest Path Graph Optimization Assignment',
    description: 'Implement Dijkstra and A* pathfinding algorithms with priority queues and analyze time complexity benchmarks.',
    class_id: 'cls-1',
    class_name: 'BCA - Section A',
    subject_name: 'Data Structures & Algorithms',
    topic_tag: 'Graph Theory',
    teacher_id: 'usr-tch-1',
    teacher_name: 'Prof. Elena Rostova',
    due_date: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
    due_time: '23:59',
    priority_level: 'medium',
    estimated_hours: 3.0,
    status: 'upcoming',
    created_at: new Date().toISOString(),
    sub_tasks: [
      {
        id: 'st-5',
        step_number: 1,
        title: 'Construct adjacency list representation and min-heap priority queue',
        due_date: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
        completed: false,
        estimated_minutes: 60,
      },
      {
        id: 'st-6',
        step_number: 2,
        title: 'Benchmark Dijkstra against Bellman-Ford on dense graphs',
        due_date: new Date(Date.now() + 4 * 86400000).toISOString().split('T')[0],
        completed: false,
        estimated_minutes: 60,
      },
    ],
  },
];

export const SEED_EVENTS: InstitutionalEvent[] = [
  {
    id: 'evt-1',
    title: 'Mid-Term Examination: Database Management Systems',
    event_type: 'exam',
    start_date: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
    end_date: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
    start_time: '09:30 AM',
    end_time: '12:30 PM',
    location: 'Auditorium Hall B',
    department_id: 'dept-1',
    department_name: 'Computer Science & Engineering',
    class_id: 'cls-1',
    target_role: 'students',
    created_by: 'usr-hod-1',
    created_by_name: 'Dr. Marcus Vance (HOD)',
    description: 'Mandatory midterm covering Units 1–3 (Relational Algebra, SQL, Normalization).',
    priority: 'critical',
  },
  {
    id: 'evt-2',
    title: 'Department Tech Fest: HackWave 2026',
    event_type: 'department_event',
    start_date: new Date(Date.now() + 10 * 86400000).toISOString().split('T')[0],
    end_date: new Date(Date.now() + 11 * 86400000).toISOString().split('T')[0],
    start_time: '10:00 AM',
    end_time: '05:00 PM',
    location: 'Main Auditorium & CS Labs',
    department_id: 'dept-1',
    department_name: 'Computer Science & Engineering',
    target_role: 'department',
    assigned_teachers: ['Prof. Elena Rostova (Technical Lead)'],
    assigned_volunteers: ['Alex Chen (Registration & Lab Setup)'],
    created_by: 'usr-hod-1',
    created_by_name: 'Dr. Marcus Vance (HOD)',
    description: 'Annual CSE Hackathon & Innovation Showcase.',
    priority: 'high',
  },
  {
    id: 'evt-3',
    title: 'Institutional Wellness & Reading Buffer Day',
    event_type: 'holiday',
    start_date: new Date(Date.now() + 6 * 86400000).toISOString().split('T')[0],
    end_date: new Date(Date.now() + 6 * 86400000).toISOString().split('T')[0],
    target_role: 'all',
    created_by: 'usr-admin-1',
    created_by_name: 'Dr. Robert Sterling (Admin)',
    description: 'Official academic pause day to support student exam revision and eliminate burnout.',
    priority: 'medium',
  },
];

export const SEED_PROJECTS: ProjectGroup[] = [
  {
    id: 'proj-1',
    class_id: 'cls-1',
    class_name: 'BCA - Section A',
    subject_name: 'Database Management Systems',
    teacher_id: 'usr-tch-1',
    teacher_name: 'Prof. Elena Rostova',
    title: 'Distributed Cloud Storage Engine',
    description: 'Building an ACID-compliant distributed key-value store with Raft consensus in TypeScript.',
    created_by: 'usr-stu-1',
    start_date: '2026-08-10',
    deadline: new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0],
    members: [
      { id: 'usr-stu-1', name: 'Alex Chen', role: 'Team Lead & Database Core', avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150', phone: '+1 (555) 890-1234' },
      { id: 'usr-stu-2', name: 'Maya Patel', role: 'Consensus & Network IO', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150', phone: '+1 (555) 678-9012' },
      { id: 'usr-stu-3', name: 'Liam Smith', role: 'Testing & Benchmark Harness', avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150', phone: '+1 (555) 789-0123' },
    ],
    tasks: [
      { id: 'pt-1', title: 'Implement write-ahead logging (WAL) storage engine', assigned_to: 'usr-stu-1', assigned_to_name: 'Alex Chen', status: 'done', due_date: '2026-08-15' },
      { id: 'pt-2', title: 'Implement Raft leader election and heartbeat ping', assigned_to: 'usr-stu-2', assigned_to_name: 'Maya Patel', status: 'in_progress', due_date: '2026-08-22' },
      { id: 'pt-3', title: 'Write concurrency benchmark and load stress test', assigned_to: 'usr-stu-3', assigned_to_name: 'Liam Smith', status: 'todo', due_date: '2026-08-28' },
      { id: 'pt-4', title: 'Prepare final architecture presentation & demo video', assigned_to: 'usr-stu-1', assigned_to_name: 'Alex Chen', status: 'todo', due_date: '2026-08-30' },
    ],
    comments: [
      {
        id: 'c-1',
        author_id: 'usr-tch-1',
        author_name: 'Prof. Elena Rostova',
        author_role: 'teacher',
        author_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
        content: 'Great progress on the WAL subsystem! Be sure to account for partial write recovery during power failures.',
        created_at: '2026-08-16T14:20:00Z',
      },
    ],
    files: [
      {
        id: 'f-1',
        name: 'Distributed_Store_Architecture_Spec.pdf',
        size: '2.8 MB',
        uploaded_by: 'Alex Chen',
        uploaded_at: '2026-08-12',
        file_type: 'PDF Document',
      },
    ],
  },
];

export const DEFAULT_STUDENT_LEARNING_PROFILE: StudentLearningProfile = {
  id: 'lp-stu-1',
  student_id: 'usr-stu-1',
  weekdayAvailabilityScore: 3, // 2-3 hours
  weekendAvailabilityScore: 3, // 4-6 hours
  theoryLearningRequirement: 3, // Needs examples
  preferredTheoryMethod: 'examples',
  preferredTheoryMethodScore: 4,
  problemUnderstandingScore: 2,
  problemBatchPreference: '5-10',
  problemBatchScore: 2,
  focusDurationScore: 3, // 30-45 mins
  longSessionToleranceScore: 2,
  longestTaskType: 'solving_problems',
  taskOrderingPreference: 'closest_deadline',
  taskOrderingScore: 4,
  revisionNeedScore: 3,
  revisionTimingPreference: 'few_days',
  stressSensitivityScore: 4,
  deadlineDifficultyType: 'underestimate_time',
  assignmentSplittingPreference: 'small_daily',
  overallWorkloadCapacity: 18, // 18 hours/week
  profileVersion: 1,
  updated_at: new Date().toISOString(),
};
